### ISSUE TITLE
Edit readme.md

### ISSUE THREAD

**Issue by Batucho** [Batucho/Oriole-DiscordBot#3]
Readme should include:
 - Intro to the project
 - How to set up the bot
 - Dependencies

**Comment by Ps066** [comment]
hey @Batucho i can design a readme file for you ... it would be intractive .. just let me know the setup and dependencies ...

**Comment by Batucho** [comment]
Introduction should have the bot's description.
Dependencies will be downloaded with ```$ pip intall -r requirements.txt```
After that yo go to the discord developer portal, create an app and add a bot to it, copy the token and create a .env file that would look smt like 
```
TOKEN=(Your token)
```
Finally you run launcher.py, we can use this so that is simpler:
```
$ python launcher.py
```

**Comment by Batucho** [comment]
I'll assign it to you @Ps066
